import { Space_Grotesk } from "next/font/google";
import "./styles/globals.css";
import Header from "../components/Header";
import Footer from "../components/Footer";

const spaceSans = Space_Grotesk({
    weight: ["400", "500", "600", "700"],
    subsets: ["latin"],
});

export const metadata = {
    title: "NeoFit",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body
                className={`${spaceSans.className} antialiased mx-auto max-w-7xl px-4 sm:px-6 lg:px-8`}
            >
                <Header />
                <div className="page">{children}</div>
                <Footer />
            </body>
        </html>
    );
}
